version: '3.6'

volumes:
  db-data:

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=testdb
    restart: always
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  app:
    build:
      context: ./images/app
    volumes:
      - ./src:/var/www/html
      - ./conf/php.smtp.ini:/usr/local/etc/php/conf.d/php_smtp.ini
    depends_on:
      - db
    restart: always

  web:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
#      - ./conf/nginx.conf:/etc/nginx/nginx.conf
#      - ./conf/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - app
    restart: always

  smtp:
    image: jeanberu/mailcatcher:latest
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: always
