// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/samples": {
            "get": {
                "tags": [
                    "samples"
                ],
                "summary": "実験用",
                "parameters": [
                    {
                        "type": "string",
                        "name": "dateUtc",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "name": "intArray",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "q1",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maxLength": 3,
                        "minLength": 2,
                        "type": "string",
                        "name": "q2",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "uuid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取得結果",
                        "schema": {
                            "$ref": "#/definitions/handler.GetSampleResponse"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "想定外のエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/surveyors": {
            "get": {
                "tags": [
                    "surveyors"
                ],
                "summary": "指定した事業所の調査員のリストを返す",
                "parameters": [
                    {
                        "maxLength": 6,
                        "type": "string",
                        "example": "000001",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "maxLength": 2,
                        "type": "string",
                        "example": "XX",
                        "name": "office-id",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "basic",
                            "detail"
                        ],
                        "type": "string",
                        "example": "detail",
                        "description": "表示形式を指定するパラメータ",
                        "name": "view",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "調査員のリスト",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.GetSurveyorsResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "想定外のエラー",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "INVALID_REQUEST"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "aaa",
                        "bbb",
                        "ccc"
                    ]
                },
                "message": {
                    "type": "string",
                    "example": "不正なリクエストです"
                }
            }
        },
        "handler.GetSampleResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "11111"
                },
                "name": {
                    "type": "string",
                    "example": "サンプル1"
                }
            }
        },
        "handler.GetSurveyorsResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "000001"
                },
                "name": {
                    "type": "string",
                    "example": "調査員1"
                },
                "office": {
                    "description": "omitemptyをつけると、nilの場合はJSONに出力されません",
                    "type": "string",
                    "example": "札幌事業所"
                },
                "office-id": {
                    "type": "string",
                    "example": "XX"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "react-ts backend API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
